CREATE TABLE IF NOT EXISTS players (
  id BIGSERIAL PRIMARY KEY,
  nickname VARCHAR(18) NOT NULL UNIQUE,
  skill_points INTEGER NOT NULL DEFAULT 1000,
  wins INTEGER NOT NULL DEFAULT 0,
  kills INTEGER NOT NULL DEFAULT 0,
  games INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS players_skill_points_idx ON players(skill_points DESC);
