CREATE TABLE IF NOT EXISTS users(
 id BIGSERIAL PRIMARY KEY,
 nickname VARCHAR(20) UNIQUE NOT NULL,
 password_hash TEXT,
 ph INTEGER NOT NULL DEFAULT 1000,
 wins INTEGER NOT NULL DEFAULT 0,
 kills INTEGER NOT NULL DEFAULT 0,
 races INTEGER NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_users_ph ON users(ph DESC);

CREATE TABLE IF NOT EXISTS race_results(
 id BIGSERIAL PRIMARY KEY,
 user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
 nickname VARCHAR(20) NOT NULL,
 position INTEGER NOT NULL,
 kills INTEGER NOT NULL DEFAULT 0,
 ph_delta INTEGER NOT NULL DEFAULT 0,
 map VARCHAR(40) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_results_user ON race_results(user_id);

-- NEON PATH 5.0 persistent progression
CREATE TABLE IF NOT EXISTS player_profiles (
 user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
 level INTEGER NOT NULL DEFAULT 1,
 xp BIGINT NOT NULL DEFAULT 0,
 prestige INTEGER NOT NULL DEFAULT 0,
 character_id INTEGER NOT NULL DEFAULT 1,
 total_wins INTEGER NOT NULL DEFAULT 0,
 total_races INTEGER NOT NULL DEFAULT 0,
 ph INTEGER NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS player_characters (
 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 character_id INTEGER NOT NULL,
 unlocked BOOLEAN NOT NULL DEFAULT FALSE,
 selected BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY(user_id,character_id)
);
CREATE INDEX IF NOT EXISTS idx_profiles_prestige ON player_profiles(prestige DESC, level DESC, xp DESC);

CREATE TABLE IF NOT EXISTS shop_items(
 id SERIAL PRIMARY KEY, code VARCHAR(64) UNIQUE NOT NULL, name VARCHAR(120) NOT NULL,
 type VARCHAR(32) NOT NULL, price INTEGER NOT NULL DEFAULT 0, rarity VARCHAR(24) NOT NULL DEFAULT 'common',
 data JSONB NOT NULL DEFAULT '{}'::jsonb, enabled BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS player_items(
 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 item_id INTEGER NOT NULL REFERENCES shop_items(id) ON DELETE CASCADE,
 owned BOOLEAN NOT NULL DEFAULT TRUE, equipped BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY(user_id,item_id)
);
