CREATE TABLE IF NOT EXISTS users(
 id BIGSERIAL PRIMARY KEY,
 nickname VARCHAR(20) UNIQUE NOT NULL,
 password_hash TEXT,
 ph INTEGER NOT NULL DEFAULT 1000,
 wins INTEGER NOT NULL DEFAULT 0,
 kills INTEGER NOT NULL DEFAULT 0,
 races INTEGER NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_users_ph ON users(ph DESC);

CREATE TABLE IF NOT EXISTS race_results(
 id BIGSERIAL PRIMARY KEY,
 user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
 nickname VARCHAR(20) NOT NULL,
 position INTEGER NOT NULL,
 kills INTEGER NOT NULL DEFAULT 0,
 ph_delta INTEGER NOT NULL DEFAULT 0,
 map VARCHAR(40) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_results_user ON race_results(user_id);
