const assert=require("assert");
const fs=require("fs");
const html=fs.readFileSync("index.html","utf8");
const css=fs.readFileSync("style.css","utf8");
const app=fs.readFileSync("app.js","utf8");
const server=fs.readFileSync("server.js","utf8");

assert(html.includes('maxlength="15"'),"room code limit missing");
assert(html.includes('E-MAIL <span>OPCIONAL</span>'),"optional email missing");
assert(html.includes('rotateNotice'),"landscape gate missing");
assert(html.includes('id="loading"'),"separate loading screen missing");
assert(html.includes('id="finish"'),"finish/podium screen missing");
assert(html.includes('id="ceoBtn"'),"CEO control missing");
assert(app.includes('quality==="low"'),"quality optimization missing");
assert(app.includes('buildTrack'),"track builder missing");
assert(app.includes('PIRATE BAY') && app.includes('ICE WORLD'),"multiple maps missing");
assert(app.includes('showLoading'),"lazy loading flow missing");
assert(server.includes('Código da sala deve ter no máximo 15 caracteres'),"server room-code validation missing");
assert(server.includes('if(r&&r.players.size===1'),"solo testing start missing");
assert(server.includes("race:finish"),"server finish event missing");
assert(server.includes("s.data.ceo&&r.players.get(s.id)"),"CEO room start must be server-authorized");
assert(server.includes("progress"),"authoritative progress missing");
assert(/cleanNick/.test(server),"nickname validation missing");
assert(/bcrypt/.test(server),"password hashing missing");
assert(!/<script>/.test("safe"));
console.log("NEON PATH 7.0 QA: OK");
